import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../js/solo_recipe_catalog.js',import.meta.url),'utf8');
let form;
const context={FormData,Blob,API:'/catalog',encodeURIComponent,studioWidget:(node,name)=>({value:name==='name_token'?'NAME':'BRAND'}),previewImageBlob:async()=>new Blob(['image']),fetch:async(url,options)=>{form=options.body;return{ok:true,json:async()=>({ok:true})};}};
vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('function replaceCatalogRunToken('),source.indexOf('function setCatalogRunButton(')),context);
vm.runInContext(source.slice(source.indexOf('async function saveCatalogPreview('),source.indexOf('async function handleCatalogPreviewExecuted(')),context);
const run={directPrompt:true,prompt:{},yearbookName:'Stacey',yearbookItem:'Sick Dolls'};
const item={kind:'template',prompt_id:'id',value:'luminous NAME wearing OUTFIT beside BRAND'};
assert.equal(context.resolvePromptYearbookDirectValues(run,item.value),'luminous Stacey wearing OUTFIT beside Sick Dolls');
await context.saveCatalogPreview({filename:'preview.png'},item,run);
assert.equal(form.get('source_prompt_snapshot'),item.value);
assert.equal(form.get('seed_source'),'catalog-run');
assert.deepEqual(JSON.parse(form.get('identity_placeholders')),[{token:'NAME',value:'Stacey'},{token:'BRAND',value:'Sick Dolls'}]);
assert.equal(item.value,'luminous NAME wearing OUTFIT beside BRAND');
assert.equal(context.replaceCatalogRunToken('NAME',['NAME'],'A$&B'),'A$&B');
await context.saveCatalogPreview({filename:'preview.png'},item);
assert.equal(form.get('source_prompt_snapshot'),item.value);
assert.equal(form.get('identity_placeholders'),null);
console.log('Yearbook frontend: portable source transport, separate temporary identities, literal replacements, and legacy caller fallback passed');
